language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      env: CUDA=7.5-18
    - os: linux
      env: CUDA=8.0.61-1
    - os : osx
      osx_image: xcode9
      env: CUDA=9.1.128
    - os : osx
      osx_image: xcode9
      env: CUDA=9.2.64


before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then ./.travis.linux.sh; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]];   then ./.travis.osx.sh;   fi


install:
  - nvcc --version
  - gcc --version
  - g++ --version

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

after_failure:
  - dmesg
  - ls -R /usr/local/cuda*
